#pragma once
#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <fstream>
#include <list>
#include <deque>
#include <chrono>

using std::ifstream;
using std::ofstream;
using std::string;
using std::vector;
using std::ostream;
using std::istream;
using std::cout;
using std::cin;
using std::istringstream;
using std::fixed;
using std::setprecision;
using std::setw;
using std::left;
using std::list;
using std::deque;
using std::to_string;

#include "student.h"
#include "student_generator.h"